### ISSUE TITLE
Issues with nixos-hardware

### ISSUE THREAD

**Issue by schrottkatze** [t2linux/nixos-t2-iso#2]
Hello, I have to write the issue here since issues aren't enabled on nixos-hardware.
I'm having the issue that when building the system it fails with this error:
```nix
error: Function called without required argument "fetchPartial" at /nix/store/q6l1by06ihnxx6irw6ifyylr2wgkllam-source/apple/t2/pkgs/t2-firmware.nix:1
(use '--show-trace' to show detailed location information)
```
This however only happens with my own custom configuration, not with the "normal" /etc/nixos/configuration.nix.
Said custom configuration can be found in https://gitlab.com/obsidianical/nix-configs, the relevant files (to my knowledge) are my flake.nix and the configuration.nix. 

The error suggests there's something wrong with your fork of nixos-hardware, which doesn't make sense considering it builds in the "normal" configuration.nix, but I'm also running out of ideas to fix this myself.

**Comment by kekrby** [comment]
You should use the [add-fetchpartial branch of my nixpkgs fork](https://github.com/kekrby/nixpkgs/tree/add-fetchpartial). This is already noted in the [README](https://github.com/kekrby/nixos-hardware/blob/master/README.md).
