### ISSUE TITLE
Can you please add a command in the README for macOS?

### ISSUE THREAD

**Issue by SolidRhino** [t2linux/nixos-t2-iso#3]
Can you please add a command to run the build process on macOS via docker or podman?

**Comment by kekrby** [comment]
Running `<podman-or-docker> run -it --privileged nixos/nix bash` will drop you into a Linux shell in which you can run the command given in the README (after cloning this repo, of course). After the build is done, you can copy the ISO to the host using `<podman-or-docker> cp`. Note that you might need to enable the `flakes` and `nix-command` experimental features.

PS: I removed the mention of `podman` and `docker` from the README as there isn't any specific reason to use them, anything that provides a Linux shell can be used. The only reason they were previously mentioned is that they were what I used.
