### ISSUE TITLE
mbp15,2 can't boot up using the iso images

### ISSUE THREAD

**Issue by coldWeather66260** [t2linux/nixos-t2-iso#4]
I used both minimal iso and gnome iso, but my mbp can't boot, with the screen always black. However, when I use vmware fusion  13.02 to test images, they work , but only on BIOS mode.

**Comment by networkException** [comment]
I've heard that people had variying levels of success with this, I'd recommend to just use the vanilla installer with an external keyboard and ethernet cable and use hardware module like in the code here later

**Comment by coldWeather66260** [comment]
> vanilla installer

Is it possible to drive the wireless card  with firmware.sh, in the case of using the vanilla installer ? 
I have tried building 6.4.9 iso myself, but screen is still  black, maybe the grub problem ?

**Comment by LawsOfScience** [comment]
Can replicate: MacBookPro16,2, latest ISO (6.4.9). Totally black screen on boot. No special graphics hardware, just a standard 16,2 with integrated graphics.
My solution is to use an older ISO that *can* boot (6.2 kernel works fine so I just use the latest 6.2 kernel ISO) and use an older hardware repository made for the kernel to install, and then update afterwards. [This article](https://dev.to/raymondgh/day-4-reinstalling-nixos-on-my-apfs-t2-intel-macbook-pro-265n) has information on the other repository (kekrby). Once you install NixOS, you *should* be able to change the kekrby hardware repository to the new NixOS one and `nixos-rebuild switch --upgrade`. This will recompile the kernel though, so be prepared for it to take a while.

**Comment by mfdorst** [comment]
Same issue here. Both the 6.4.9 and 6.4.2 versions just result in a black screen for me. The 6.2 version does boot though.

**Comment by mineichen** [comment]
> Same issue here. Both the 6.4.9 and 6.4.2 versions just result in a black screen for me. The 6.2 version does boot though.

Same here. I tested 6.4.9 with QEMU, which worked fine. Booting it from USB  didn't work. 6.4.2 did neither. After dd'ing 6.2. onto a USB flashdrive, I finally got past the blackscreen. I have a Macbook 15' Macbook (2019 Edition) with Radeon Pro 555X 4GB. 
In case this matters for the firmware: I recdntly updated to OSX Sonoma 14.2.1

**Comment by LawsOfScience** [comment]
I was able to successfully boot by cloning this repo, running `nix flake update`, and then `nix flake build .#t2-iso-minimal`. I've opened #5 to hopefully get this fixed. Like I state in the PR, I think the failure to boot is due to a regression in the bootloader that was also noticed by non-T2 NixOS users.

**Comment by lairtonlelis** [comment]
For those looking for a quick fix, release 6.1.7 boots just fine on my MacBookPro16,2:

https://github.com/t2linux/nixos-t2-iso/releases/tag/v6.1.7
